### ISSUE TITLE
🧹 Standardize Admin Portal

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/design-gc-digital-talent#50]
## Title:
Standardize admin portal

## Description:
This work should help improve usability across the site, users will be able to predict more accurately the behavior of the site by standardize the way things look and behave.

We will be breaking up the work in smaller chunks and organize it by type of work and page to make sure this can be tackled slowly over time. We will be making a ticket for each small change.

The following fixes apply to EVERY item on the admin portal

## To-do:

**1. Adding "Archive" (Soft delete) crud action
2. Replace page forms for inline forms
3. Add table of contents to information page
4. Replace breadcrumb navigation for tab navigation
5. Standardize Title and Subtitle
6. Make item name clickable on table pages**

### 1. Add 'Archive' crud action

- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/30
- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/51
- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/52
- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/54
- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/38
- [ ] Add 'Archive' crud action to "User" page ( )
- [ ] Add 'Archive' crud action to "Request" page ( )
- [ ] Add 'Archive' crud action to "Pool" page ( )

### 2. Replace page form for inline form

- [ ] Replace page form for inline form on "Skill" page ( )
- [ ] Replace page form for inline form on "Skill family" page ( )
- [ ] Replace page form for inline form on "Classification" page ( )
- [ ] Replace page form for inline form on "Department" page ( )
- [ ] Replace page form for inline form on "Team" page ( )
- [ ] Replace page form for inline form on "User" page ( )
- [ ] Replace page form for inline form on "Request" page ( )
- [ ] Replace page form for inline form on "Pool" page ( )

### 3. Add table of contents to information page

- [ ] Add table of contents to skill page ( )
- [ ] Add table of contents to skill family page ( )
- [ ] Add table of contents to classification page ( )
- [ ] Add table of contents to department page ( )
- [ ] Add table of contents to team page ( )
- [ ] Add table of contents to user page ( )
- [ ] Add table of contents to request page ( )
- [ ] Add table of contents to pool page ( )

### 4. Replace breadcrumb navigation for tab navigation

- [ ] Replace breadcrumb navigation for tab navigation on skill page ( )
- [ ] Replace breadcrumb navigation for tab navigation on skill family page ( )
- [ ] Replace breadcrumb navigation for tab navigation on classification page ( )
- [ ] Replace breadcrumb navigation for tab navigation on department page ( )
- [ ] Replace breadcrumb navigation for tab navigation on team page ( )
- [ ] Replace breadcrumb navigation for tab navigation on user page ( )
- [ ] Replace breadcrumb navigation for tab navigation on request page ( )
- [ ] Replace breadcrumb navigation for tab navigation on pool page ( )

### 5. Standardize Title and Subtitle

- [ ] Standardize Title and Subtitle on skill page ( )
- [ ] Standardize Title and Subtitle on skill family page ( )
- [ ] Standardize Title and Subtitle on classification page ( )
- [ ] Standardize Title and Subtitle on department page ( )
- [ ] Standardize Title and Subtitle on team page ( )
- [ ] Standardize Title and Subtitle on user page ( )
- [ ] Standardize Title and Subtitle on request page ( )
- [ ] Standardize Title and Subtitle on pool page ( )

### 6. Make item name clickable on table pages

- [ ] Make item name clickable on table skill page ( )
- [ ] Make item name clickable on table skill family page ( )
- [ ] Make item name clickable on table classification page ( )
- [ ] Make item name clickable on table department page ( )
- [ ] Make item name clickable on table team page ( )
- [ ] Make item name clickable on table user page ( )
- [ ] Make item name clickable on table request page ( )
- [ ] Make item name clickable on table pool page ( )
